-- 코드를 작성해주세요
WITH RECURSIVE A AS (
    SELECT 1 AS GEN, ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT 1+A.GEN, E1.ID, E1.PARENT_ID
      FROM ECOLI_DATA E1 INNER JOIN A
      ON A.ID = E1.PARENT_ID
     )
SELECT ID
  FROM A
  WHERE GEN = 3;