SELECT DISTINCT CC.CAR_ID, CC.CAR_TYPE,
30*CC.DAILY_FEE*(1-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP WHERE CC.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상')/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON CC.CAR_ID = RH.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP -- 이 조인으로 아래 BETWEEN 절이 간단해짐
ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE CC.CAR_TYPE IN ('세단','SUV')
AND CC.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH WHERE '202211' BETWEEN TO_CHAR(RH.START_DATE,'YYYYMM') AND TO_CHAR(RH.END_DATE,'YYYYMM'))
AND 30*CC.DAILY_FEE*(1- DP.DISCOUNT_RATE/100) BETWEEN 500000 AND 2000000-1 -- 정수값만 가지면 가능
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;