-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, CITY || ' ' || STREET_ADDRESS1 || (CASE WHEN STREET_ADDRESS2 IS NOT NULL THEN ' '|| STREET_ADDRESS2 END) AS 전체주소, SUBSTR(TLNO,1,3) || '-' || SUBSTR(TLNO,4,4) || '-' || SUBSTR(TLNO,-4) AS 전화번호 -- 오라클은 LEFT RIGHT 없음
FROM (SELECT WRITER_ID, COUNT(WRITER_ID) AS USER_CNT FROM USED_GOODS_BOARD GROUP BY WRITER_ID) A INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.USER_CNT >= 3 -- alias 지정해야 사용 가능
ORDER BY 1 DESC;