-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH, GENDER, COUNT(DISTINCT INFO.USER_ID) AS USERS -- 회원 수를 집계하므로 DISTINCT! EXTRACT(YEAR FROM SALES_DATE)도 사용 가능
FROM USER_INFO INFO INNER JOIN ONLINE_SALE SALE
ON INFO.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE,'MM'), GENDER
ORDER BY 1,2,3;