-- 코드를 입력하세요
SELECT TO_CHAR(OS.SALES_DATE,'YYYY') AS YEAR, EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH, COUNT(DISTINCT INFO.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT INFO.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'),1) AS PURCHASED_RATIO
FROM USER_INFO INFO JOIN ONLINE_SALE OS
ON INFO.USER_ID = OS.USER_ID
WHERE TO_CHAR(INFO.JOINED, 'YYYY') = '2021'
GROUP BY TO_CHAR(OS.SALES_DATE,'YYYY'), EXTRACT(MONTH FROM OS.SALES_DATE)
ORDER BY YEAR, MONTH;