-- 코드를 작성해주세요
WITH RECURSIVE A AS ( -- CTE: Common Table Expression
    SELECT 1 AS GEN, ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT 1+A.GEN, E1.ID, E1.PARENT_ID
      FROM ECOLI_DATA E1 INNER JOIN A
      ON A.ID = E1.PARENT_ID
     )
SELECT COUNT(ID) AS COUNT, A.GEN AS GENERATION
  FROM A
  WHERE A.ID NOT IN (SELECT PARENT_ID FROM A WHERE PARENT_ID IS NOT NULL)
  GROUP BY A.GEN
  ORDER BY A.GEN;