-- 코드를 입력하세요
SELECT FLAVOR FROM
(SELECT FLAVOR, SUM(TOTAL_ORDER)
FROM (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF UNION ALL SELECT FLAVOR, TOTAL_ORDER FROM JULY)
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC FETCH FIRST 3 ROWS ONLY);