-- 코드를 입력하세요
SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, DR.MCDP_CD, DR.DR_NAME, APNT_YMD
FROM PATIENT PT, DOCTOR DR, APPOINTMENT AP
WHERE PT.PT_NO = AP.PT_NO AND DR.DR_ID =  AP.MDDR_ID
AND AP.APNT_CNCL_YN = 'N' AND TO_CHAR(APNT_YMD,'YYYYMMDD') = '20220413'
AND DR.MCDP_CD = 'CS'
ORDER BY APNT_YMD;