-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS DEV, SKILLCODES SC
WHERE DEV.SKILL_CODE&SC.CODE IN (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End')
ORDER BY ID
/*SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS DEV
WHERE DEV.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') !=0
ORDER BY ID*/
;