-- 코드를 입력하세요
SELECT PROF.MEMBER_NAME, REV.REVIEW_TEXT, TO_CHAR(REV.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM (SELECT MEMBER_ID, COUNT(MEMBER_ID)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 2 DESC FETCH FIRST 1 ROWS WITH TIES) SUB1 INNER JOIN REST_REVIEW REV
    ON SUB1.MEMBER_ID = REV.MEMBER_ID INNER JOIN MEMBER_PROFILE PROF
    ON REV.MEMBER_ID = PROF.MEMBER_ID
ORDER BY REV.REVIEW_DATE, REV.REVIEW_TEXT;