-- 코드를 작성해주세요
SELECT B.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO A INNER JOIN ITEM_TREE B INNER JOIN ITEM_INFO C
ON C.ITEM_ID = B.ITEM_ID
AND B.PARENT_ITEM_ID = A.ITEM_ID
WHERE A.RARITY = 'RARE'
ORDER BY 1 DESC;