-- 코드를 작성해주세요
SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A, SKILLCODES B
WHERE (A.SKILL_CODE div (SELECT B.CODE FROM SKILLCODES B WHERE B.NAME = 'Python')) % 2 = 1 OR
(A.SKILL_CODE div (SELECT B.CODE FROM SKILLCODES B WHERE B.NAME = 'C#')) % 2 = 1
ORDER BY A.ID;