-- 코드를 작성해주세요
SELECT SUM(C.SCORE) AS SCORE, C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_EMPLOYEES B INNER JOIN HR_GRADE C
ON B.EMP_NO = C.EMP_NO
GROUP BY C.EMP_NO
ORDER BY 1 DESC
LIMIT 1; -- [offset, ] num 혹은 num OFFSET offset