-- 코드를 작성해주세요
/* FIND_IN_SET https://school.programmers.co.kr/questions/76142, GROUP_CONCAT */
SELECT 
(CASE WHEN DEV.SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND DEV.SKILL_CODE&(SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'A' -- 중복되는 비트가 있으면 nonzero임을 이용한 것
WHEN DEV.SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
WHEN DEV.SKILL_CODE&(SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C' END) AS GRADE
, ID, EMAIL
FROM DEVELOPERS DEV, SKILLCODES SC
WHERE DEV.SKILL_CODE&SC.CODE IN (SELECT CODE FROM SKILLCODES WHERE NAME IN ('Python','C#') OR CATEGORY = 'Front End')
GROUP BY GRADE, ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID

/*SELECT 
(CASE WHEN DEV.SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND DEV.SKILL_CODE&(SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'A' -- 중복되는 비트가 있으면 nonzero임을 이용한 것
WHEN DEV.SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
WHEN DEV.SKILL_CODE&(SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C' END) AS GRADE
, ID, EMAIL
FROM DEVELOPERS DEV LEFT JOIN SKILLCODES SC
ON DEV.SKILL_CODE = SC.CODE
GROUP BY GRADE, ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID*/;